set MATLAB=C:\Program Files\MATLAB\R2013a
"C:\PROGRA~1\MATLAB\R2013a\bin\win64\gmake" -f ARDroneHover.mk  EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 OPTS="-DON_TARGET_WAIT_FOR_START=0"
