#!/bin/sh
ifconfig eth0 up
iwconfig eth0 essid ENSEM-SAMI
ifconfig eth0 192.168.1.1
route add default gw 192.168.1.254 eth0
wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -i eth0 -Dwext -B
